### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bobprokop** [cladera/videojs-offset#2]
Downloaded the ZIP and demo doesn't work. Google Analytics error on the hosted version of video.js.

Tried using a local copy of video.js and error is gone but nothing happens.

Attached the existing demo function to an event call (trigger w/button) and nothing happens.

Is there a working example/demo of this in action? It seems like it would be the perfect solution — and one that ought to be baked into video.js by default.

Thanks!

**Comment by cladera** [comment]
Hello @bobprokop ,

First of all, I'd like to apologise for the unacceptable delay. 

Indeed, executing demo's index.html in local mode throws a Google Analytics error. I've never seen that before because I always used a localhost server, which I recommend you to do as well. Anyway, you'll find a running demo here: http://cladera.github.io/videojs-offset/.

What are you trying to accomplish?
